character_mapping:
  CHU²:
  - 35
  LAYER:
  - 31
  LOCK:
  - 32
  MASKING:
  - 33
  PAREO:
  - 34
  三角初华:
  - 3
  上原绯玛丽:
  - 8
  丰川祥子:
  - 1
  丸山彩:
  - 16
  二叶筑紫:
  - 29
  今井莉莎:
  - 23
  仓田真白:
  - 26
  八幡海铃:
  - 4
  八潮瑠唯:
  - 30
  冰川日菜:
  - 17
  冰川纱夜:
  - 22
  凑友希那:
  - 21
  北泽育美:
  - 13
  千早爱音:
  - 37
  大和麻弥:
  - 19
  奥泽美咲:
  - 15
  宇田川亚子:
  - 24
  宇田川巴:
  - 9
  山吹沙绫:
  - 4
  市谷有咲:
  - 5
  广町七深:
  - 28
  弦卷心:
  - 11
  户山香澄:
  - 1
  松原花音:
  - 14
  桐谷透子:
  - 27
  椎名立希:
  - 40
  濑田薰:
  - 12
  牛込里美:
  - 3
  白金燐子:
  - 25
  白鹭千圣:
  - 18
  祐天寺若麦:
  - 5
  美竹兰:
  - 6
  羽泽鸫:
  - 10
  花园多惠:
  - 2
  若叶睦:
  - 2
  若宫伊芙:
  - 20
  要乐奈:
  - 38
  长崎素世:
  - 39
  青叶摩卡:
  - 7
  高松灯:
  - 36
parsing:
  default_narrator_name: ' '
  max_short_speaker_name_length: 6
  max_speaker_name_length: 50
patterns:
  speaker_pattern: ^([\w\s]+)\s*[：:]\s*(.*)$
quotes:
  quote_categories:
    中文单引号 ‘...’:
    - ‘
    - ’
    中文引号 “...”:
    - “
    - ”
    日文书名号 『...』:
    - 『
    - 』
    日文引号 「...」:
    - 「
    - 」
    英文单引号 '...':
    - ''''
    - ''''
    英文双引号 "...":
    - '"'
    - '"'
  quote_pairs:
    '"': '"'
    '''': ''''
    ‘: ’
    “: ”
    「: 」
    『: 』
